spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://${DB_HOST:localhost}:5432/pichat}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1996}
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    continue-on-error: true
