server:
  port: ${PORT:8088}
  servlet:
    context-path: /api/v1
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  mail:
    properties:
      mail:
        smtp:
          username: ${HAIRX_MAIL:mypichatapp@gmail.com}
          password: ${HAIRX_MAIL_PASSWORD:pichat1996}
com:
  cloudinary:
    cloud_name: ${cloud_name:piusaremieye}
    api_key: ${api_key:475476531299184}
    api_secret: ${api_secret:Y1gJDPyzNDrn1AwMtj8-b15ewlY}

springdoc:
  swagger-ui:
    url: /api/v1/swagger-config.yaml
    path: /api-doc